# Generated by Django 3.2.6 on 2021-12-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_postmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
