# Generated by Django 3.2.6 on 2021-12-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_alter_postmodel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
