# Generated by Django 3.2.6 on 2021-12-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_postmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
