# Generated by Django 3.2.6 on 2021-12-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_postmodel_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='upload',
        ),
    ]
