# Generated by Django 4.0.4 on 2022-05-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
